### Formula

$$
\left|v_{i, j}\right|^{2} \prod_{k=1 ; k \neq i}^{n}\left(\lambda_{i}(A)-\lambda_{k}(A)\right)=\prod_{k=1}^{n-1}\left(\lambda_{i}(A)-\lambda_{k}\left(M_{j}\right)\right)
$$

### NumPy

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
np.__version__

'1.17.2'

In [11]:
np.set_printoptions(precision=18)

In [2]:
def sub_matrix_np0(A, n, j):
    row, row[j] = np.ones(n, dtype=bool), False
    return A[row][:,row]

def sub_matrix_np1(A, n, j):
    row, row[j:] = np.arange(n-1), np.arange(n-1)[j:]+1
    return A[row][:,row]

def sub_matrix_np2(A, n, j):
    row = np.arange(n)
    row = np.concatenate([row[:j], row[j+1:]])
    return A[row][:,row]

In [5]:
def eigv_ij_tao_np(A, i, j):

    eigvals = LA.eigvals(A)
    M_j = sub_matrix_np0(A, eigvals.shape[0], j)
    eigvals_M_j = LA.eigvals(M_j)
    eigvals_M_j = eigvals_M_j - eigvals[i]
    eigvals, eigvals[i] = eigvals - eigvals[i], 1.0

    return np.prod(eigvals_M_j) / np.prod(eigvals)

In [6]:
A = np.array([[3.20233843, 2.06764157, 2.88108853, 3.04719701, 1.35948144,
        2.56403503, 1.45954379, 2.13631733, 1.53986513, 3.25995899],
       [2.06764157, 2.29127686, 2.1014315 , 2.70700189, 1.39188518,
        2.29620216, 1.40820018, 1.53013976, 1.63189934, 2.82578892],
       [2.88108853, 2.1014315 , 3.50400477, 3.47397131, 1.76088485,
        3.23409601, 1.32428533, 2.77130533, 2.23036096, 3.42124947],
       [3.04719701, 2.70700189, 3.47397131, 4.73687997, 2.20972905,
        3.77378375, 2.34901207, 2.48563082, 2.19559837, 4.13322167],
       [1.35948144, 1.39188518, 1.76088485, 2.20972905, 1.59570009,
        2.14854992, 1.1252818 , 1.94769495, 1.34582313, 2.1726746 ],
       [2.56403503, 2.29620216, 3.23409601, 3.77378375, 2.14854992,
        3.90925026, 2.11631829, 2.99858233, 2.44964915, 3.61299442],
       [1.45954379, 1.40820018, 1.32428533, 2.34901207, 1.1252818 ,
        2.11631829, 2.14092743, 1.13700682, 1.22321095, 2.05145548],
       [2.13631733, 1.53013976, 2.77130533, 2.48563082, 1.94769495,
        2.99858233, 1.13700682, 3.41056761, 2.08224044, 3.02608265],
       [1.53986513, 1.63189934, 2.23036096, 2.19559837, 1.34582313,
        2.44964915, 1.22321095, 2.08224044, 2.12302856, 2.41838461],
       [3.25995899, 2.82578892, 3.42124947, 4.13322167, 2.1726746 ,
        3.61299442, 2.05145548, 3.02608265, 2.41838461, 4.55396155]])
A

array([[3.20233843, 2.06764157, 2.88108853, 3.04719701, 1.35948144,
        2.56403503, 1.45954379, 2.13631733, 1.53986513, 3.25995899],
       [2.06764157, 2.29127686, 2.1014315 , 2.70700189, 1.39188518,
        2.29620216, 1.40820018, 1.53013976, 1.63189934, 2.82578892],
       [2.88108853, 2.1014315 , 3.50400477, 3.47397131, 1.76088485,
        3.23409601, 1.32428533, 2.77130533, 2.23036096, 3.42124947],
       [3.04719701, 2.70700189, 3.47397131, 4.73687997, 2.20972905,
        3.77378375, 2.34901207, 2.48563082, 2.19559837, 4.13322167],
       [1.35948144, 1.39188518, 1.76088485, 2.20972905, 1.59570009,
        2.14854992, 1.1252818 , 1.94769495, 1.34582313, 2.1726746 ],
       [2.56403503, 2.29620216, 3.23409601, 3.77378375, 2.14854992,
        3.90925026, 2.11631829, 2.99858233, 2.44964915, 3.61299442],
       [1.45954379, 1.40820018, 1.32428533, 2.34901207, 1.1252818 ,
        2.11631829, 2.14092743, 1.13700682, 1.22321095, 2.05145548],
       [2.13631733, 1.53013976, 2.7713053

In [8]:
n = A.shape[0]

In [9]:
# v_n
[eigv_ij_tao_np(A, i=n-1, j=j) for j in range(n)]

[0.010078898355312161,
 0.008526097435704025,
 0.03552221239921944,
 0.021411824331722774,
 0.17690013381018135,
 0.5189551148981736,
 0.06059635621137234,
 0.00246512246354466,
 0.10612109694238948,
 0.059423143152378614]

In [10]:
%%timeit
[eigv_ij_tao_np(A, i=n-1, j=j) for j in range(n)]

759 µs ± 7.15 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
# eigenvectors from numpy.linalg
(LA.eig(A)[1]**2)[:,n-1].reshape(-1,1)

array([[0.010078898355311885],
       [0.008526097435703766],
       [0.035522212399219155],
       [0.021411824331722753],
       [0.17690013381018374 ],
       [0.5189551148981745  ],
       [0.0605963562113716  ],
       [0.002465122463544841],
       [0.10612109694238844 ],
       [0.059423143152379225]])

In [13]:
%%timeit
(LA.eig(A)[1]**2)[:,n-1].reshape(-1,1)

39.4 µs ± 289 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### PyTorch

In [14]:
import torch

In [41]:
torch.__version__

'1.1.0'

In [15]:
torch.set_printoptions(precision=18)

In [16]:
def sub_matrix_torch0(A, n, j):
    row, row[j] = torch.ones(n, dtype=torch.bool), False
    return A[row][:,row]

def sub_matrix_torch1(A, n, j):
    row, row[j:] = torch.arange(n-1), torch.arange(n-1)[j:]+1
    return A[row][:,row]

def sub_matrix_torch2(A, n, j):
    row = torch.arange(n)
    row = torch.cat([row[:j], row[j+1:]])
    return A[row][:,row]

In [17]:
def eigv_ij_tao_torch(A, i, j):

    eigvals, _ = torch.symeig(A)
    M = sub_matrix_torch2(A, eigvals.shape[0], j)
    eigvals_M_j, _ = torch.symeig(M)
    eigvals_M_j = eigvals_M_j - eigvals[i]
    eigvals, eigvals[i] = eigvals - eigvals[i], 1.0

    return torch.prod(eigvals_M_j) / torch.prod(eigvals)

In [18]:
A_torch = torch.tensor(A)

In [19]:
n = A_torch.shape[0]

In [20]:
[eigv_ij_tao_torch(A_torch, i=n-8, j=j) for j in range(n)]

[tensor(0.010078898355311965, dtype=torch.float64),
 tensor(0.008526097435700507, dtype=torch.float64),
 tensor(0.035522212399216449, dtype=torch.float64),
 tensor(0.021411824331723325, dtype=torch.float64),
 tensor(0.176900133810184573, dtype=torch.float64),
 tensor(0.518955114898170700, dtype=torch.float64),
 tensor(0.060596356211371390, dtype=torch.float64),
 tensor(0.002465122463545969, dtype=torch.float64),
 tensor(0.106121096942389470, dtype=torch.float64),
 tensor(0.059423143152376595, dtype=torch.float64)]

In [21]:
%%timeit
[eigv_ij_tao_torch(A_torch, i=n-8, j=j) for j in range(n)]

851 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
%%timeit
eig, eigv = torch.eig(A_torch, eigenvectors=True)
eigv[:,n-1]**2

35.4 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Test

In [26]:
A = np.random.rand(200, 200)
A = A.dot(A.T)
A

array([[67.47723926317164 , 54.19423484384579 , 54.27515904605383 , ...,
        49.879068195082326, 52.45239609483475 , 49.408191932642495],
       [54.19423484384579 , 71.04782742790326 , 53.85157684964276 , ...,
        52.12536300728289 , 54.07596344138458 , 52.375034082709284],
       [54.27515904605383 , 53.85157684964276 , 69.68410454172101 , ...,
        50.52068209024865 , 53.62038066497085 , 49.4446241172947  ],
       ...,
       [49.879068195082326, 52.12536300728289 , 50.52068209024865 , ...,
        64.06442820289213 , 52.68081075931759 , 48.13930731991735 ],
       [52.45239609483475 , 54.07596344138458 , 53.62038066497085 , ...,
        52.68081075931759 , 70.45479014414464 , 48.559403460835036],
       [49.408191932642495, 52.375034082709284, 49.4446241172947  , ...,
        48.13930731991735 , 48.559403460835036, 66.04338254189733 ]])

In [27]:
n = A.shape[0]

In [28]:
%%timeit
[eigv_ij_tao_np(A, i=n-1, j=j) for j in range(n)]

3.17 s ± 51.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
A_torch = torch.tensor(A)

In [33]:
%%timeit
[eigv_ij_tao_torch(A_torch, i=n-1, j=j) for j in range(n)]

556 ms ± 1.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
%%timeit
(LA.eig(A)[1]**2)[:,n-1].reshape(-1,1)

11.9 ms ± 393 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [32]:
%%timeit
eig, eigv = torch.eig(A_torch, eigenvectors=True)
eigv[:,n-1]**2

10.5 ms ± 91.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
